apiVersion: batch/v1
kind: Job
metadata:
  name: dcm2niix-conversion
  namespace: chris-students-c9344e
spec:
  template:
    spec:
      containers:
      - name: dcm2niix
        image: registry.access.redhat.com/ubi9/ubi:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            # Install dcm2niix
            dnf install -y wget unzip
            cd /tmp
            wget https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20230411/dcm2niix_lnx.zip
            unzip dcm2niix_lnx.zip
            chmod +x dcm2niix
            
            # Create output directory
            mkdir -p /data/NIFTI
            
            # Run conversion
            ./dcm2niix -z y -b n -o /data/NIFTI /data/DICOM
            
            echo "Conversion complete!"
            ls -la /data/NIFTI
        volumeMounts:
        - name: dicom-storage
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dicom-storage
        persistentVolumeClaim:
          claimName: dicom-pvc
  backoffLimit: 2
