apiVersion: batch/v1
kind: Job
metadata:
  name: dcm2niix-conversion
  namespace: chris-students-c9344e
spec:
  template:
    spec:
      containers:
      - name: dcm2niix
        image: fnndsc/pl-dcm2niix:latest
        args: ["dcm2niixw", "-z", "y", "-b", "n", "/data/DICOM", "/data/NIFTI"]
        volumeMounts:
        - name: dicom-storage
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dicom-storage
        persistentVolumeClaim:
          claimName: dicom-pvc
  backoffLimit: 2
