apiVersion: batch/v1
kind: Job
metadata:
  name: dcm2niix-conversion
  namespace: chris-students-c9344e
spec:
  template:
    spec:
      containers:
      - name: dcm2niix
        image: registry.access.redhat.com/ubi9/ubi:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            # Install dcm2niix
            dnf install -y wget unzip
            cd /tmp
            wget https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20230411/dcm2niix_lnx.zip
            unzip dcm2niix_lnx.zip
            chmod +x dcm2niix
            
            # Run conversion
            ./dcm2niix -z y -b n -o /outgoing /incoming
            
            echo "Conversion complete!"
            ls -la /outgoing
        volumeMounts:
        - name: dicom-data
          mountPath: /incoming
        - name: nifti-data
          mountPath: /outgoing
      restartPolicy: Never
      volumes:
      - name: dicom-data
        persistentVolumeClaim:
          claimName: dicom-data
      - name: nifti-data
        persistentVolumeClaim:
          claimName: nifti-data
  backoffLimit: 2
