apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: chris-students-c9344e
spec:
  ports:
    - port: 3100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loki
